version: '3.8'
services:
  llm-app:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        PIPELINE_MODE: ${PIPELINE_MODE}
    ports:
      - "8080:8080"
    env_file:
      - ./.env
    stdin_open: true
    tty: true
